name: pokemon_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  bloc_test: ^9.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/

